name = "TE Server"

[mods]
mods = [
    {title = "TaCZ Tweaks",side = "both",added = "2026-09-27 17:38"},
    {title = "[UNOFFICIAL] TaCZ 1.21.1 NeoForge Port",side = "both",added = "2026-09-27 17:38"},
    {title = "The Hordes",side = "both",added = "2026-09-27 17:38"},
    {title = "Biomes O' Plenty",side = "both",added = "2026-09-27 17:38"},
    {title = "Tectonic",side = "both",added = "2026-09-27 17:38"},
    {title = "Incendium Legacy",side = "both",added = "2026-09-27 17:38"},
    {title = "Formations Nether",side = "server",added = "2026-09-27 17:38"},
    {title = "Formations Overworld",side = "server",added = "2026-09-27 17:38"},
    {title = "Towns and Towers",side = "both",added = "2026-09-27 17:38"},
    {title = "End Remastered",side = "both",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Caves",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Bridges",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Dungeons",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Mineshafts",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Strongholds",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Desert Temples",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Jungle Temples",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Ocean Monuments",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Witch Huts",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better Nether Fortresses",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Better End Island",side = "server",added = "2026-09-27 17:38"},
    {title = "YUNG's Cave Biomes",side = "both",added = "2026-09-27 19:38"},
    {title = "YUNG's Extras",side = "server",added = "2026-09-27 20:10"},
    {title = "[Let's Do] Farm & Charm",side = "both",added = "2026-09-27 20:35"},
    {title = "[Let's Do] Meadow",side = "both",added = "2026-09-27 20:35"},
    {title = "[Let's Do] Vinery",side = "both",added = "2026-09-27 20:35"},
    {title = "[Let's Do] Bakery - Farm&Charm Compat",side = "both",added = "2026-09-27 20:35"},
    {title = "[Let's Do] Brewery - Farm&Charm Compat",side = "both",added = "2026-09-27 20:35"},
    {title = "[Let's Do] HerbalBrews",side = "both",added = "2026-09-27 20:35"},
    {title = "[Let's Do] Camping",side = "both",added = "2026-09-27 20:35"},
    {title = "Farmer's Delight",side = "both",added = "2026-09-27 20:35"},
    {title = "More Delight (for Farmer's Delight)",side = "both",added = "2026-09-27 20:35"},
    {title = "Veggies Delight (A Farmer's Delight Add-on)",side = "both",added = "2026-09-27 20:35"},
    {title = "Chef's Delight - Farmer's Delight Villagers",side = "both",added = "2026-09-27 20:35"},
    {title = "Farmer's Knives",side = "both",added = "2026-09-27 20:35"},
    {title = "Connected Glass",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Windows",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Fences and Walls",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Bridges",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Doors",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Roofs",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Stairs",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Furniture",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Paths and Pavings",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Paintings",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Trapdoors",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Holidays",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Lights and Lamps",side = "both",added = "2026-09-27 20:53"},
    {title = "Macaw's Biomes O' Plenty",side = "both",added = "2026-09-27 20:53"},
    {title = "Fusion Connected Blocks",side = "client",added = "2026-09-27 21:17",type = "resourcepack"},
    {title = "Complementary Shaders - Unbound",side = "client",added = "2026-09-27 21:17",type = "shader"},
    {title = "Fusion Block Transitions",side = "client",added = "2026-09-27 21:17",type = "resourcepack"},
    {title = "Sodium",side = "client",added = "2026-09-27 21:17"},
    {title = "Iris Shaders",side = "client",added = "2026-09-27 21:17"},
    {title = "Just Enough Items (JEI)",side = "both",added = "2026-09-27 21:17"},
    {title = "Mouse Tweaks",side = "client",added = "2026-09-27 21:17"},
    {title = "Jade 🔍",side = "both",added = "2026-09-27 21:17"},
    {title = "AppleSkin",side = "both",added = "2026-09-27 21:17"},
    {title = "Double Doors",side = "server",added = "2026-09-27 21:17"},
    {title = "SelectiveBounds",side = "client",added = "2026-09-27 21:17"},
    {title = "FallingTree",side = "both",added = "2026-09-27 21:17"},
    {title = "Controlling",side = "client",added = "2026-09-27 21:17"},
    {title = "Visual Workbench",side = "both",added = "2026-09-27 21:17"},
    {title = "Shulker Box Tooltip",side = "both",added = "2026-09-27 21:17"},
    {title = "Integrated Dynamics",side = "both",added = "2026-09-27 21:17"},
    {title = "Integrated Tunnels",side = "both",added = "2026-09-27 21:17"},
    {title = "Integrated Terminals",side = "both",added = "2026-09-27 21:17"},
    {title = "Integrated Crafting",side = "both",added = "2026-09-27 21:17"},
    {title = "Integrated Scripting",side = "both",added = "2026-09-27 21:17"},
    {title = "Integrated REST",side = "both",added = "2026-09-27 21:17"},
    {title = "Integrated NBT",side = "both",added = "2026-09-27 21:17"},
    {title = "CC: Tweaked",side = "both",added = "2026-09-27 21:17"},
    {title = "Animal Pens",side = "both",added = "2026-09-27 21:17"},
    {title = "Sophisticated Backpacks",side = "both",added = "2026-09-27 21:17"},
    {title = "Sophisticated Storage",side = "both",added = "2026-09-27 21:17"},
    {title = "Better Days",side = "both",added = "2026-09-27 21:17"},
    {title = "Simple Voice Chat",side = "both",added = "2026-09-27 21:17"},
    {title = "Sit",side = "both",added = "2026-09-27 21:17"},
    {title = "Lootr",side = "both",added = "2026-09-27 21:17"},
    {title = "Crawl",side = "both",added = "2026-09-27 21:17"},
    {title = "Serene Seasons",side = "both",added = "2026-09-27 21:17"},
    {title = "Cold Sweat",side = "both",added = "2026-09-27 21:17"},
    {title = "Ender's Delight",side = "both",added = "2026-09-27 21:23"},
    {title = "Cuisine Delight",side = "both",added = "2026-09-27 21:23"},
    {title = "Realistic Bees",side = "both",added = "2026-09-27 22:23"},
    {title = "Guard Villagers",side = "both",added = "2026-09-27 22:23"},
    {title = "Illager Invasion",side = "both",added = "2026-09-27 22:23"},
    {title = "L2 Hostility",side = "both",added = "2026-09-27 22:23"},
    {title = "Rechiseled",side = "both",added = "2026-09-27 22:23"},
    {title = "FTB Library (NeoForge)",side = "both",added = "2026-09-27 22:42",platform = "curseforge",cf_ref = "ftb-library-forge",cf_file_id = "8858846",cf_filename = "ftb-library-neoforge-2101.1.36.jar"},
    {title = "FTB Teams (NeoForge)",side = "both",added = "2026-09-27 22:42",platform = "curseforge",cf_ref = "ftb-teams-forge",cf_file_id = "8724782",cf_filename = "ftb-teams-neoforge-2101.1.11.jar"},
    {title = "FTB Chunks (NeoForge)",side = "both",added = "2026-09-27 22:42",platform = "curseforge",cf_ref = "ftb-chunks-forge",cf_file_id = "8791113",cf_filename = "ftb-chunks-neoforge-2101.1.22.jar"},
]
