name = "TE Server"

[mods]
mods = [
    {title = "Fusion Connected Blocks",side = "client",added = "2026-09-22 14:00",type = "resourcepack"},
    {title = "Connected Glass",side = "both",added = "2026-09-22 14:00"},
    {title = "Complementary Shaders - Unbound",side = "client",added = "2026-09-22 14:00",version = "r5.9.3",type = "shader"},
    {title = "Fusion Block Transitions",side = "client",added = "2026-09-22 14:02",type = "resourcepack"},
    {title = "Sodium",side = "client",added = "2026-09-22 14:16"},
    {title = "Iris Shaders",side = "client",added = "2026-09-22 14:17"},
    {title = "Biomes O' Plenty",side = "both",added = "2026-09-22 15:46"},
    {title = "Incendium Legacy",side = "both",added = "2026-09-22 15:46"},
    {title = "Stellarity",side = "both",added = "2026-09-22 15:46"},
    {title = "Tectonic",side = "both",added = "2026-09-22 15:46"},
    {title = "Integrated Dynamics",side = "both",added = "2026-09-22 16:37"},
    {title = "Integrated Tunnels",side = "both",added = "2026-09-22 16:37"},
    {title = "Integrated Terminals",side = "both",added = "2026-09-22 16:37"},
    {title = "Integrated Crafting",side = "both",added = "2026-09-22 16:37"},
    {title = "Integrated Scripting",side = "both",added = "2026-09-22 16:37"},
    {title = "Integrated NBT",side = "both",added = "2026-09-22 16:37"},
    {title = "Colossal Chests",side = "both",added = "2026-09-22 16:37"},
    {title = "Just Enough Items (JEI)",side = "both",added = "2026-09-22 16:41"},
    {title = "Integrated REST",side = "both",added = "2026-09-22 17:17"},
    {title = "CC: Tweaked",side = "both",added = "2026-09-22 18:23"},
    {title = "Mouse Tweaks",side = "client",added = "2026-09-22 18:27"},
    {title = "Jade 🔍",side = "both",added = "2026-09-22 18:27"},
    {title = "AppleSkin",side = "both",added = "2026-09-22 18:27"},
    {title = "Double Doors",side = "server",added = "2026-09-22 18:27"},
    {title = "Better Days",side = "both",added = "2026-09-22 18:27"},
    {title = "SelectiveBounds",side = "client",added = "2026-09-22 18:27"},
    {title = "FallingTree",side = "both",added = "2026-09-22 18:27"},
    {title = "GraveStone Mod",side = "both",added = "2026-09-22 18:27"},
    {title = "NetherPortalFix",side = "server",added = "2026-09-22 18:31"},
    {title = "Controlling",side = "client",added = "2026-09-22 18:31"},
    {title = "Building Wands",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Windows",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Fences and Walls",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Bridges",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Doors",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Roofs",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Stairs",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Furniture",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Paths and Pavings",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Paintings",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Lights and Lamps",side = "both",added = "2026-09-22 18:39"},
    {title = "Macaw's Holidays",side = "both",added = "2026-09-22 18:39"},
    {title = "Rechiseled",side = "both",added = "2026-09-22 18:47"},
    {title = "Formations Nether",side = "server",added = "2026-09-22 18:47"},
    {title = "Formations Overworld",side = "server",added = "2026-09-22 18:47"},
    {title = "Ore Growth",side = "both",added = "2026-09-22 18:47"},
    {title = "Realistic Bees",side = "both",added = "2026-09-22 18:53"},
    {title = "Let Me Despawn",side = "server",added = "2026-09-22 18:53"},
    {title = "Packet Fixer",side = "both",added = "2026-09-22 18:53"},
    {title = "Concurrent Chunk Management Engine (NeoForge)",side = "both",added = "2026-09-22 18:53"},
    {title = "Xaero's Minimap",side = "both",added = "2026-09-22 18:53"},
    {title = "Xaero's World Map",side = "both",added = "2026-09-22 18:53"},
    {title = "Undead Nights - Zombie Horde Nights / Hordes",side = "both",added = "2026-09-22 19:01"},
    {title = "Hostile Mobs Improve Over Time",side = "both",added = "2026-09-22 19:01"},
    {title = "[UNOFFICIAL]TaCZ Renovated",side = "both",added = "2026-09-22 19:03",platform = "curseforge",cf_ref = "unofficial-tacz-renovated",cf_file_id = "8873087",cf_filename = "tacz-1.1.8+neoforge.26.2.R3-hotfix2.jar"},
    {title = "TaCZ Tweaks (Refabricated)",side = "both",added = "2026-09-22 19:03",platform = "curseforge",cf_ref = "tacz-tweaks-refabricated",cf_file_id = "8711570",cf_filename = "tacztweaks-2.14.2+neoforge.26.2.Beta-1.jar"},
    {title = "Large Ore Deposits",side = "server",added = "2026-09-22 19:08"},
    {title = "Simple Voice Chat",side = "both",added = "2026-09-22 19:13"},
    {title = "Dream Displays",side = "both",added = "2026-09-22 19:13"},
    {title = "Sit",side = "both",added = "2026-09-22 19:13"},
    {title = "Sophisticated Backpacks",side = "both",added = "2026-09-22 19:33"},
    {title = "Shulker Box Tooltip",side = "both",added = "2026-09-22 19:33"},
    {title = "More Culling",side = "client",added = "2026-09-22 19:33"},
    {title = "Lithium",side = "both",added = "2026-09-22 19:33"},
    {title = "FerriteCore",side = "both",added = "2026-09-22 19:33"},
    {title = "ScalableLux",side = "both",added = "2026-09-22 19:33"},
    {title = "Clumps",side = "both",added = "2026-09-22 19:33"},
    {title = "Visual Workbench",side = "both",added = "2026-09-22 19:33"},
    {title = "Towns and Towers",side = "both",added = "2026-09-22 19:33"},
    {title = "Nature's Compass",side = "both",added = "2026-09-22 19:33"},
    {title = "Explorer's Compass",side = "both",added = "2026-09-22 19:33"},
    {title = "Immersive Pillagers",side = "both",added = "2026-09-22 19:33"},
    {title = "SecurityCraft",side = "both",added = "2026-09-22 19:33"},
    {title = "Guard Villagers",side = "both",added = "2026-09-22 19:33"},
    {title = "Illager Invasion",side = "both",added = "2026-09-22 19:33"},
    {title = "Lootr",side = "both",added = "2026-09-22 19:33"},
    {title = "Cooking for Blockheads",side = "both",added = "2026-09-22 19:53"},
    {title = "Farmer's Delight 26 Neo Ver",side = "both",added = "2026-09-22 19:53",platform = "curseforge",cf_ref = "farmers-delight-26-neo-ver",cf_file_id = "8928315",cf_filename = "FarmersDelight-26.2-1.3.3-fix4.jar"},
    {title = "Immersive Melodies",side = "both",added = "2026-09-22 20:12"},
    {title = "Immersive Aircraft",side = "both",added = "2026-09-22 20:12"},
    {title = "Crawl",side = "both",added = "2026-09-22 21:09"},
    {title = "Archers (RPG Series)",side = "both",added = "2026-09-23 07:58"},
    {title = "Paladins & Priests (RPG Series)",side = "both",added = "2026-09-23 07:58"},
    {title = "Wizards (RPG Series)",side = "both",added = "2026-09-23 07:58"},
    {title = "Rogues & Warriors (RPG Series)",side = "both",added = "2026-09-23 07:58"},
    {title = "Skill Tree (RPG Series)",side = "both",added = "2026-09-23 07:58"},
    {title = "Jewelry (RPG Series)",side = "both",added = "2026-09-23 07:59"},
    {title = "Relics (RPG Series)",side = "both",added = "2026-09-23 07:59"},
    {title = "Arsenal (RPG Series)",side = "both",added = "2026-09-23 07:59"},
    {title = "Armory (RPG Series)",side = "both",added = "2026-09-23 07:59"},
    {title = "Better Combat",side = "both",added = "2026-09-23 08:14"},
    {title = "Combat Roll",side = "both",added = "2026-09-23 08:14"},
    {title = "Gazebos (RPG Series)",side = "server",added = "2026-09-23 08:14"},
    {title = "Village Taverns (RPG Series)",side = "both",added = "2026-09-23 08:14"},
    {title = "Tough As Nails",side = "both",added = "2026-09-23 19:45"},
    {title = "Serene Seasons",side = "both",added = "2026-09-23 19:45"},
    {title = "Animal Pens",side = "both",added = "2026-09-23 22:25"},
]
